name: demo_api_project
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0  # More flexible & powerful than http
  retrofit: ^4.0.3  # Generates API client code for Dio (optional)
  json_annotation: ^4.8.1  # Helps with JSON serialization

  # State Management (Choose one)
  flutter_bloc: ^8.1.3  # Bloc & Cubit for managing app state
  provider: ^6.1.1  # Alternative state management (simpler)

  # Authentication & Secure Storage
  flutter_secure_storage: ^9.0.0  # Store JWT tokens securely
  shared_preferences: ^2.2.2  # Store user session preferences
  jwt_decoder: ^2.0.1  # Decode JWT tokens to extract user data

  # Firebase (If using Firebase Auth & Storage)
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2  # If using Firebase for image uploads

  # Image Upload & Picker
  image_picker: ^1.1.2  # Select images from gallery or camera
  path_provider: ^2.1.2  # Manage file storage

  # UI & Utility
  fluttertoast: ^8.2.4  # Show toast messages
  intl: ^0.19.0  # Date formatting & localization

  # Geolocation (If events have locations)
  geolocator: ^11.0.0  # Get user’s current location
  geocoding: ^2.1.1  # Convert coordinates to address

  # File Upload & HTTP Multipart (If not using Firebase)

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  device_info_plus: ^11.3.0
  image_cropper: ^9.0.0
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^8.0.5  # Generates REST API client
  build_runner: ^2.4.8  # Needed for code generation
  json_serializable: ^6.7.1  # Helps with JSON serialization

  flutter_lints: ^5.0.0  # Linting rules for Flutter

flutter:
  uses-material-design: true
